name: Node.js
on: [push]

env:
  CI: true
  ENCRYPTION: sha512
  DB_URL: mysql://root:password@0.0.0.0:3307/test
  DB_PASS: password
  DB_PORT: 3307
  DB_SCHEMA: test
  DB_TYPE: mariadb
  DB_USER: root

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use mariadb 10
        uses: getong/mariadb-action@v1.1
        with:
          container port: ${{ env.DB_PORT }}
          host port: ${{ env.DB_PORT }}
          mysql root password: ${{ env.DB_PASS }}
          mysql database: ${{ env.DB_SCHEMA }}
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-test-${{ matrix.node-version }}-${{ env.cache-name }}-
            ${{ runner.OS }}-test-${{ matrix.node-version }}-
            ${{ runner.OS }}-test-
            ${{ runner.OS }}-
      - name: Yarn install
        run: yarn
      - name: Test
        run: yarn test
